# Site settings
title: Portfolio
description: My portfolio Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhavya Sharma
user_description: Hey! I'm Bhavya, an undergraduate student, keenly interested in Robotics, particularly in control of Biomimetic Robots and underactuated robotics.I am currently working on control of legged robots. Apart from Robotics, I enjoy programming and development. You can check my projects below!
user_title: Robotics Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum



exclude: ['package.json', 'src' , 'node_modules']
