# Site settings
title: Bhavya Sharma's portfolio
description: Updated portfolio


# User settings
username: Bhavya Sharma
user_description: portfolio
user_title: Software Developer / Startup Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum



exclude: ['package.json', 'src' , 'node_modules']
