# Site settings
title: Bhavya Sharma's portfolio
description: Hey, I'm Bhavya!
I'm a full stack software developer with two years of experience. I work on end to end web development and Azure based network architechture.
I am also enthusiastic about entrepreneurship and am looking forward to starting my own venture or joining a promising idea.

Other than these, 
I love to hit the gym and am always up for a game of chess!

email -  bhavyas2603@gmail.com
number -  +91-8949485816
chess.com - @coppenhager


# User settings
username: Bhavya Sharma
user_description: portfolio
user_title: Software Developer / Startup Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum



exclude: ['package.json', 'src' , 'node_modules']
