# Site settings
title: Portfolio
description: My portfolio Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhavya Sharma
user_description: Hey! I'm Bhavya, a final year undergrad student, keenly Interested in Software development. I worked on build and control of robots in the earlier years of my undergrad.Eventually,I found interest in software development and programming with data structures and algorithms.I am looking for an Internship in a software development or web development role,for any duration of time between :(1 August 2021, 31 May 2022)  I am looking for a job for the role of SDE or SRE, I can join the job full time from 1 June,2022. 
user_title: Software Developer / Programming Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum



exclude: ['package.json', 'src' , 'node_modules']
