# Site settings
title: Portfolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhavya Sharma
user_description: About me
user_title: Robotics Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
