# Site settings
title: Portfolio
description: My portfolio Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhavya Sharma
user_description: Hey! I'm Bhavya, a final year undergrad student.I have experience in Web Development,Software Development and Data Structures and Algorithms. I am looking for a job for the role of SDE1, I can join full-time from May 2022. 
user_title: Software Developer / Programming Enthusiast
email: bhavyas2603@gmail.com
#twitter_username: lorem_ipsum
github_username:  bs2603
#gplus_username:  lorem_ipsum



exclude: ['package.json', 'src' , 'node_modules']
